package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:04:22.992-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "MathCalc")
@XmlSeeAlso({ObjectFactory.class})
public interface MathCalc {

    @WebMethod
    @RequestWrapper(localName = "doAddition", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoAddition")
    @ResponseWrapper(localName = "doAdditionResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoAdditionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int doAddition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "doSubtraction", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoSubtraction")
    @ResponseWrapper(localName = "doSubtractionResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoSubtractionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int doSubtraction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "doModulo", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoModulo")
    @ResponseWrapper(localName = "doModuloResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoModuloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int doModulo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "doDivision", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoDivision")
    @ResponseWrapper(localName = "doDivisionResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoDivisionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int doDivision(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "doMultiplication", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoMultiplication")
    @ResponseWrapper(localName = "doMultiplicationResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DoMultiplicationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int doMultiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
