
package com.revature.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:04:22.942-04:00
 * Generated source version: 3.3.0
 *
 */
public final class MathCalc_MathCalcImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.revature.com/", "mathCalcService");

    private MathCalc_MathCalcImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MathCalcService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MathCalcService ss = new MathCalcService(wsdlURL, SERVICE_NAME);
        MathCalc port = ss.getMathCalcImplPort();

        {
        System.out.println("Invoking doAddition...");
        int _doAddition_arg0 = 0;
        int _doAddition_arg1 = 0;
        int _doAddition__return = port.doAddition(_doAddition_arg0, _doAddition_arg1);
        System.out.println("doAddition.result=" + _doAddition__return);


        }
        {
        System.out.println("Invoking doSubtraction...");
        int _doSubtraction_arg0 = 0;
        int _doSubtraction_arg1 = 0;
        int _doSubtraction__return = port.doSubtraction(_doSubtraction_arg0, _doSubtraction_arg1);
        System.out.println("doSubtraction.result=" + _doSubtraction__return);


        }
        {
        System.out.println("Invoking doModulo...");
        int _doModulo_arg0 = 0;
        int _doModulo_arg1 = 0;
        int _doModulo__return = port.doModulo(_doModulo_arg0, _doModulo_arg1);
        System.out.println("doModulo.result=" + _doModulo__return);


        }
        {
        System.out.println("Invoking doDivision...");
        int _doDivision_arg0 = 0;
        int _doDivision_arg1 = 0;
        int _doDivision__return = port.doDivision(_doDivision_arg0, _doDivision_arg1);
        System.out.println("doDivision.result=" + _doDivision__return);


        }
        {
        System.out.println("Invoking doMultiplication...");
        int _doMultiplication_arg0 = 0;
        int _doMultiplication_arg1 = 0;
        int _doMultiplication__return = port.doMultiplication(_doMultiplication_arg0, _doMultiplication_arg1);
        System.out.println("doMultiplication.result=" + _doMultiplication__return);


        }

        System.exit(0);
    }

}
