package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:04:22.999-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "mathCalcService",
                  wsdlLocation = "http://localhost:8080/SOAPMath/mathservice?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class MathCalcService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "mathCalcService");
    public final static QName MathCalcImplPort = new QName("http://ws.revature.com/", "MathCalcImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPMath/mathservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MathCalcService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPMath/mathservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MathCalcService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MathCalcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathCalcService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MathCalcService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MathCalcService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MathCalcService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MathCalc
     */
    @WebEndpoint(name = "MathCalcImplPort")
    public MathCalc getMathCalcImplPort() {
        return super.getPort(MathCalcImplPort, MathCalc.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathCalc
     */
    @WebEndpoint(name = "MathCalcImplPort")
    public MathCalc getMathCalcImplPort(WebServiceFeature... features) {
        return super.getPort(MathCalcImplPort, MathCalc.class, features);
    }

}
